language: php

matrix:
    include:
        - php: 7.1
          env: deps=low
        - php: 7.2
        - php: 7.3
    fast_finish: true
    
before_script:
  - phpenv config-rm xdebug.ini || echo "XDebug is not enabled"
  - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; else composer install; fi

script:
  - ./vendor/bin/phpspec run -f pretty
  - ./vendor/bin/behat --profile=ci --format=progress
